const path=require('path')
let ext=path.extname('C:\\Users\\anush\\OneDrive\\Desktop\\node\\f1.txt')
let baseName=path.basename('C:\\Users\\anush\\OneDrive\\Desktop\\node\\f1.txt')
console.log(ext)
console.log(baseName)
console.log(__filename)
console.log(__dirname)